### ISSUE TITLE
why not add span info for slots?

### ISSUE THREAD

**Issue by lexmen318** [thu-coai/CrossWOZ#4]
Hi,

I wonder why not add span info for slots,  just like MultiWOZ?

Thx a lot!

**Comment by zqwerty** [comment]
Because sometimes the value of the slot doesn't appear in the utterance:
1. Request, NoOffer, Select, General intent
2. hotel facilities slot for inform intent
3. other reference issue or value normalization

Also, a simple string matching algorithm can help you get the span info easily.
By the way, the original MultiWOZ doesn't have span info.

**Comment by zqwerty** [comment]
To get the span automatically, you can refer to https://github.com/thu-coai/CrossWOZ/blob/master/convlab2/nlu/jointBERT/crosswoz/preprocess.py

**Comment by lexmen318** [comment]
OK. Thx a lot for your reply on time! However, I would like to share my understanding:
1) span info is very helpful for NLU module to catch attention to the slots;
2) for those slots that does not exactly equal to there appearance inside utterances, that's much more helpful, just like to teaching a language learner to understand  some words' real implication.
